### ISSUE TITLE
无法永久删除默认导语

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [facexl/AI-chat#1]
导语添加后可保存，但是无法永久删除默认导语，只能在当前窗口中保持删除状态，也无法排序各个导语的优先级

**Comment by facexl** [comment]
感谢反馈，验证bug属实，正在修复中

**Comment by facexl** [comment]
> 导语添加后可保存，但是无法永久删除默认导语，只能在当前窗口中保持删除状态，也无法排序各个导语的优先级

你好 Bug 已经修复，请更新到 0.0.2 版本，导语优先级目前按照最后一次使用的导语为默认，感谢您的宝贵意见

**Comment by facexl** [comment]
@systemoutprintlnhelloworld thanks

**Comment by systemoutprintlnhelloworld** [comment]
> @systemoutprintlnhelloworld thanks

大大辛苦了❤️❤️忘了看通知没看到您的消息

**Comment by systemoutprintlnhelloworld** [comment]
> @systemoutprintlnhelloworld thanks

作者辛苦了❤️❤️忘了看通知没看到您的消息
